name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions for GCloud
on: [push]
jobs:
  job_id:
    # Add "id-token" with the intended permissions.
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v3'

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/81869977343/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider'
        service_account: 'default-service-account@fast-api-230516.iam.gserviceaccount.com'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        version: '>= 363.0.0'

    - name: 'Build and deploy'
      run: 'gcloud builds submit --region="europe-west1" --config cloudbuild.yaml .'